### ISSUE TITLE
Additional sub folder with IntunePackage.intunewin

### ISSUE THREAD

**Issue by Rokory** [MSEndpointMgr/Intune#12]
Running the Add-IntuneWin32App create a sub folder in the folder containing the intunewin package file with the name of the setup file containing an IntunePackage.intunewin, which is a duplicate of the file given in the FilePath parameter.

If this is necessary, it should be deleted after finishing the command.

**Comment by NickolajA** [comment]
The file is actually not a duplicate, it's essentially the encrypted file that's being uploaded originally extracted from within the packaged .intunewin file. It makes sense to clean it up though afterwards, i'll fix that for 1.2.0.
