### ISSUE TITLE
Get-IntuneWin32AppAissgnment

### ISSUE THREAD

**Issue by Rokory** [MSEndpointMgr/Intune#15]
A command Get-IntuneWin32AppAssignment, that returns the app assignments in a data structure that can be applied using the Add-IntuneWin32AppAssignment would help in many scenarios.

**Comment by NickolajA** [comment]
I've actually created a new function as of today that retrieves each instance of existing assignments. You can follow the development of the new version 1.2.0 here:

https://github.com/MSEndpointMgr/Intune/projects/1
