### ISSUE TITLE
Powershell 7 compatibility

### ISSUE THREAD

**Issue by malcolmardalon** [MSEndpointMgr/Intune#19]
Are these modules compatible with Powershell 7.0.3 ?  Everything seem to work fine on Powershell 5, but on Powershell 7 I get the following warnings/errors: 
WARNING: Failed to determine if an update to the PSIntuneAuth module is necessary, will continue
WARNING: Failure to acquire access token. Response with access token was null

Please help would be amazing to be able to incorporate this into our work!

**Comment by Dirk-Manderin** [comment]
I just came here to ask the same thing.  I'm using some functions in my script that require Powershell 7, so I can't switch back to 5.1.

**Comment by Dirk-Manderin** [comment]
I did some more research, and Az should be used in Powershell 6/7.  The AzureAD module will still work, but requires being run in compatibility mode.  https://stackoverflow.com/a/63646425/14127491  Haven't tried it yet though.

**Comment by Dirk-Manderin** [comment]
Are there any plans to update PSIntuneAuth to use MSAL instead of ADAL, since ADAL has been deprecated?  ADAL doesn't appear to work with Powershell 7.

**Comment by JankeSkanke** [comment]
Check out our new module. This is using MSAL and requires MSAL.PS module. This module is verified to work on PowerShell 7.x
 
[https://www.powershellgallery.com/packages/MSGraphRequest/1.1.3](https://www.powershellgallery.com/packages/MSGraphRequest/1.1.3)

[https://github.com/MSEndpointMgr/MSGraphRequest](https://github.com/MSEndpointMgr/MSGraphRequest)
