### ISSUE TITLE
Add support for AzureADPreview module

### ISSUE THREAD

**Issue by ghvanderweg** [MSEndpointMgr/Intune#2]
Could you check for either the AzureAD or AzureADPreview module as a prerequisite? I only have the AzureADPreview module installed, which would work fine.

**Comment by ghvanderweg** [comment]
To clarify, this was meant for the PSIntuneAuth module

**Comment by michael-rknudsen-dk** [comment]
@NickolajA Hi Nickolai, i am also interested in support for the AzureADPreview module to PSIntuneAuth. 

If you agree on this i would be happy to add it, maybe using a switch parameter, something like -AllowAzureADPreview.
