### ISSUE TITLE
This module wont work on Azure Automation 

### ISSUE THREAD

**Issue by tigerdeccan** [MSEndpointMgr/Intune#34]
This Module checks if AzureAD module is installed and it checks and install it . also clobber with AzureADpreview. 

This code is not working in Azure Automation account because on Azure Automation sandbox they dont allow installing modules . can you please fix this behavior

**Comment by JankeSkanke** [comment]
Azure Automation do allow for module installation. 
[https://docs.microsoft.com/en-us/azure/automation/shared-resources/modules](https://docs.microsoft.com/en-us/azure/automation/shared-resources/modules?WT.mc_id=EM-MVP-5002085)
