### ISSUE TITLE
AzureADDeviceID is missing in CustomInventory

### ISSUE THREAD

**Issue by MarkusBux** [MSEndpointMgr/Intune#41]
In our environment, some devices do not report the AzureADDeviceID.

After analysing the script and the affected devices, it seems, that these devices PSChildName is the AzureADDeviceID instead of the Certificate thumbprint.

<img width="1452" alt="image" src="https://user-images.githubusercontent.com/46794913/144065770-0c56bc0d-2667-4bbb-a8ff-38d85324d73e.png">

<img width="737" alt="image" src="https://user-images.githubusercontent.com/46794913/144066112-046c3039-40a7-410b-8211-6dd96e1068c9.png">

**Comment by JankeSkanke** [comment]
This Project is moved and issue fixed in latest update in new repo
