### ISSUE TITLE
Install-CloudLAPS_SchTask.ps1 OS language dependency

### ISSUE THREAD

**Issue by lucafabbri365** [MSEndpointMgr/Intune#48]
Hello,
I deployed **Install-CloudLAPS_SchTask.ps1** to Windows 10 devices (different OS languages) through Intune; CloudLAPS was deployed correctly to all targeted devices, however for some devices the _Status_ column returns **Failed**.
Looking at _IntuneManagementExtension.log_ on these clients I found this error:

`[PowerShell] Fail, the details are {"Version":1,"SigningCode":649,"SigningMsg":"(Success) AccountId:cea65ad1-a3f8-45a2-ae0d-56f2ebfa2f75,PolicyId:e9bc75ec-b503-4d3f-8ed6-d3bdf5750708,Type:1,Enforce: Audit. OSVersion:10.0.19044,AgentVersion:1.52.256.0. ","ExecutionMsg":"Install-CloudLAPSClient : Failed to Set ACL on Cloud LAPS Client Script. Error message: Ausnahme beim Aufrufen von \r\n\"RemoveAccessRuleAll\" mit 1 Argument(en):  \"Manche oder alle Identitätsverweise konnten nicht übersetzt werden.\"\r\nIn C:\\Program Files (x86)\\Microsoft Intune Management \r\nExtension\\Policies\\Scripts\\879ed8b6-166a-419c-a7e1-ccae81b43443_e9bc75ec-b503-4d3f-8ed6-d3bdf5750708.ps1:622 Zeichen:1\r\n+ Install-CloudLAPSClient\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException\r\n    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-CloudLAPSClient\r\n \r\n\r\n"}`

It seems to fail while executing the **RemoveAccessRuleAll**:

`593 - $ACL2 = Get-ACL -Path $CloudLAPSClientScriptPath`
`594 - $ACE_Remove = New-Object system.security.AccessControl.FileSystemAccessRule("Users", "Read", "Allow")`
`595 - $ACL2.RemoveAccessRuleAll($ACE_Remove)`.

I suppose the problem is related to **FileSystemAccessRule**; The _Users_ name (I assume it is referred to _BUILTIN\Users_) depends on OS language. So converting it to a language neutral:

`593 - $ACL2 = Get-ACL -Path $CloudLAPSClientScriptPath`
`594 - $BuiltinUsers = New-Object System.Security.Principal.SecurityIdentifier -ArgumentList @([System.Security.Principal.WellKnownSidType]::BuiltinUsersSid, $null)`
`595 - $ACE_Remove = New-Object system.security.AccessControl.FileSystemAccessRule($BuiltinUsers, "Read", "Allow")`
`596 - $ACL2.RemoveAccessRuleAll($ACE_Remove)`

References:

- [language neutral FileSystemAccessRule](https://stackoverflow.com/questions/54222763/language-neutral-filesystemaccessrule) (stackoverflow)
- [WellKnownSidType Enum](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.wellknownsidtype?view=net-6.0) (Microsoft Docs)

What about ?

**Comment by byteben** [comment]
Hi Luca, thanks for the feedback. I agree and will make the change you outlined. Thanks :)

**Comment by byteben** [comment]
Commits on Apr 19, 2022
Version 1.0.1 - (2022-04-19) 
Added Universal Language support for enumerating "USERS" when modifying the ACL of the script path. Thanks lucafabbri365

**Comment by lucafabbri365** [comment]
> Hi Luca, thanks for the feedback. I agree and will make the change you outlined. Thanks :)

You are welcome @byteben !!!
