### ISSUE TITLE
Checking Autopilot profile assignment status and rebooting

### ISSUE THREAD

**Issue by pontusr** [MSEndpointMgr/Intune#7]
Thanks for this - I came across your script looking to improve my own. A couple of things on my wish-list:
1. Add an option to force the script to wait after the sync until an Autopilot profile has been assigned to the device so that we know the device is ready to be deployed using Autopilot after the script has run.
2. Add an option to reboot the device using `shutdown /r /t 0` to make sure we remove the "empty" Autopilot profile that would have been created if network was available at beginning of OOBE. (Only works on 1809 and later: https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/troubleshooting#profile-download)

Using these two in combination would allow for even less manual work required to enroll and deploy a device.

I might come back to add this in a PR unless you beat me to it - would you consider accepting it in that case?

**Comment by mind-racer** [comment]
This will be great, would help automate the process
